name: Test

on:
  push: {branches: [master, test]}
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        include:
          - {platform: ubuntu-latest, python: "3.11", toxenv: "py311"}
          - {platform: ubuntu-latest, python: "3.12", toxenv: "py312"}
          - {platform: ubuntu-latest, python: "3.13", toxenv: "py313"}
          - {platform: ubuntu-latest, python: "3.13", toxenv: "lint"}
          - {platform: macos-latest, python: "3.13", toxenv: "py313"}
          - {platform: windows-latest, python: "3.13", toxenv: "py313"}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
      - name: Test with Tox
        run: uvx --with=tox-uv tox -e ${{ matrix.toxenv }}
      - name: Upload coverage data to codecov.io
        uses: codecov/codecov-action@v5
